### ISSUE TITLE
Technology Readiness Levels for Omics Protocols

### ISSUE THREAD

**Issue by jodievandekamp** [BeBOP-OBON/miop#21]
Need to review existing Technology Readiness Level (TRL) definitions and scope and choose most appropriate and/or adapt for 'omics protocols to be included in the Maturity Level field. Known definitions are provided by: NASA, FOO, IMOS, OBPS. Final product should be a table with definitions for levels, hosted on our git repo and linked to through MIOP specification.

**Comment by raissameyer** [comment]
For the purpose of MIOP, we would opt for including "Maturity level"
The OBPS has this definition
"Maturity Level
If applicable, enter the maturity level of the
methodology in the document
N/A: where maturity level not applicable
Mature: Methodologies are well demonstrated for a given objective,
documented and peer reviewed; methods are commonly used by
more than one organization ~(TRL 7-9)~
Pilot or Demonstrated: Methodologies are being demonstrated and
validated; limited consensus exists on widespread use or in any given
situation ~(TRL 4-6)~
Concept: A methodology is being developed at one institution(s) but
has not been agreed to by the community; requirements and form
for a methodology are understood ~(TRL 1-3)~"

We would remove the TLRs, because, as noted above, these are not applicable for methodological documents 

We could also add a supplementary field where people can link back to how they tested their protocol. This links to another issue

**Comment by raissameyer** [comment]
Closing this issue as it has been addressed by  @kpitz in the above commit.

(added the following
> Enter the maturity level of the methodology in the document. 
      Mature: Methodologies are well demonstrated for a given objective, documented and peer reviewed; methods are commonly used by more than one organization.
      Pilot or Demonstrated: Methodologies are being demonstrated and validated; limited consensus exists on widespread use or in any given situation.
      Concept: A methodology is being developed at one institution(s) but has not been agreed to by the community; requirements and form for a methodology 

)
